### ISSUE TITLE
xrld path issues?

### ISSUE THREAD

**Issue by xbeaudouin** [sasu-drooz/Domoticz-Teleo-veolia#1]
Hello,

Is there any limitation on python path issues with Domoticz.

I use python 3.4, and installed py34-xlrd (on freebsd), the command line python 3.4 does not complains when doing import xlrd, but the Teleo does: 

```
Error: (Teleo) failed to load 'plugin.py', Python Path used was '/usr/local/domoticz/plugins/Teleo-veolia/:/usr/local/lib/python34.zip:/usr/local/lib/python3.4/:/usr/local/lib/python3.4/plat-freebsd11:/usr/local/lib/python3.4/lib-dynload'.
Error: (Eau) Module Import failed, exception: 'ImportError'
Error: (Eau) Module Import failed: ' Name: xlrd'
```

Seems the the enbedded python 3.4 doesn't look at : 
```
/usr/local/lib/python3.4/site-packages/xlrd
/usr/local/lib/python3.4/site-packages/xlrd/__init__.py
/usr/local/lib/python3.4/site-packages/xlrd/__pycache__

```

Have an idea (BTW this plugins is an awsome idea).

**Comment by zaraki673** [comment]
salut, oui y a ptit probleme pour ouvrir les lib externes,

regarde ou se trouve ton plugin python xlrd sur ta config et fait un lin
logique ou une copie vers les repertoire cité ds ton log
(/usr/local/lib/python3.4/
par exemple ou directe ds le repertoire Teleo-veolia (
/usr/local/domoticz/plugins/Teleo-veolia/)

le plugin est pas tres stable encore, pas le temps de m en occuper, y a une
version script a executer en tache cron qui , il me semble, fonctionne
mieux
https://easydomoticz.com/forum/viewtopic.php?f=10&t=2272&start=20#p32270

c est la meme base que j'ai mis en mode plugin :D

2017-05-20 12:40 GMT+02:00 Xavier Beaudouin <notifications@github.com>:

**Comment by xbeaudouin** [comment]
Merci ca marche :)
